spring:
  application.name: core-api
  profiles.active: local
  servlet.multipart.max-file-size: 3MB
  jpa:
    open-in-view: false
server:
  tomcat:
    max-connections: 2048
    threads:
      max: 50
      min-spare: 25
    connection-timeout: 10000
springdoc:
  api-docs:
    path: /api-docs
  default-consumes-media-type: application/json;charset=UTF-8
  default-produces-media-type: application/json;charset=UTF-8

file.dir: ${FILE_DIR}

---
spring.config.activate.on-profile: local
spring:
  h2.console:
    enabled: true
    path: /h2-console
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:FOFODB;MODE=MySQL
    username: sa
    password:
    hikari:
      connection-timeout: 10000
  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        show_sql: true
        format_sql: true

---
spring.config.activate.on-profile: dev
server:
  ssl:
    key-store: ${KEY_STORE_PATH}
    key-store-type: PKCS12
    key-store-password: ${KEY_STORE_PASSWORD}
spring:
  datasource:
    url: ${FOFO_DB_URL}
    username: ${FOFO_DB_USERNAME}
    password: ${FOFO_DB_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      connection-timeout: 10000
  jpa:
    hibernate:
      ddl-auto: update

---
spring.config.activate.on-profile: prod
server:
  ssl:
    key-store: ${KEY_STORE_PATH}
    key-store-type: PKCS12
    key-store-password: ${KEY_STORE_PASSWORD}
spring:
  datasource:
    url: ${FOFO_DB_URL}
    username: ${FOFO_DB_USERNAME}
    password: ${FOFO_DB_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      connection-timeout: 10000
  jpa:
    hibernate:
      ddl-auto: none
