spring:
  datasource:
#    url: jdbc:h2:mem:local;MODE=MySQL;
    url: jdbc:mysql://152.69.207.57:3306/FOFODB?useSSL=false
    username: fofofe
    password: fofofe!
    dirver-class-name: com.mysql.cj.jdbc.Driver
#  h2:
#    console:
#      enabled: true
#      path: /h2-console

  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
        show_sql: true
        format_sql: true
#  logging.lever:
#    org.hibernate.SQL: debug
#    org.hibernate.type: trace