spring.application.name: core-api
spring.profiles.active: local

server:
  tomcat:
    max-connections: 2048
    threads:
      max: 50
      min-spare: 25
spring:
  jpa:
    open-in-view: false

springdoc:
  api-docs:
    path: /api-docs
  default-consumes-media-type: application/json
  default-produces-media-type: application/json
  swagger-ui:
    path: /
    disable-swagger-default-url: true
    display-request-duration: true
    operations-sorter: alpha
---
spring.config.activate.on-profile: local
spring:
  h2:
    console:
      enabled: true
      path: /h2-console
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:FOFODB;MODE=MySQL
    username: sa
    password:
  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        show_sql: true
        format_sql: true

logging.level:
  org.hibernate.SQL: debug
  org.hibernate.type: trace

---
spring.config.activate.on-profile: prod
spring:
  datasource:
    url: ${FOFO_DB_URL}
    username: ${FOFO_DB_USERNAME}
    password: ${FOFO_DB_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: create-drop
