spring.application.name: core-api
spring.profiles.active: local

server:
  servlet.multipart.max-file-size: 2MB
  tomcat:
    max-connections: 2048
    threads:
      max: 50
      min-spare: 25
spring.jpa.open-in-view: false
springdoc:
  api-docs:
    path: /api-docs
  default-consumes-media-type: application/json
  default-produces-media-type: application/json

---
spring.config.activate.on-profile: local
spring:
  h2.console:
    enabled: true
    path: /h2-console
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:FOFODB;MODE=MySQL
    username: sa
    password:
  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        show_sql: true
        format_sql: true

logging.level.org.hibernate.orm.jdbc.bind: trace

file.dir: ${FILE_DIR}

aes.key: ${AES_KEY}

---
spring.config.activate.on-profile: dev
server:
  ssl:
    key-store: ${KEY_STORE_PATH}
    key-store-type: PKCS12
    key-store-password: ${KEY_STORE_PASSWORD}
spring:
  datasource:
    url: ${FOFO_DB_URL}
    username: ${FOFO_DB_USERNAME}
    password: ${FOFO_DB_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update

aes.key: ${AES_KEY}

---
spring.config.activate.on-profile: prod
server:
  ssl:
    key-store: ${KEY_STORE_PATH}
    key-store-type: PKCS12
    key-store-password: ${KEY_STORE_PASSWORD}
spring:
  datasource:
    url: ${FOFO_DB_URL}
    username: ${FOFO_DB_USERNAME}
    password: ${FOFO_DB_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: none

aes.key: ${AES_KEY}
